name: hreader
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
    sdk: ^3.5.4

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.8
    sqflite_common_ffi: ^2.3.4+3
    path_provider: ^2.1.2
    file_picker: ^8.1.2
    logging: ^1.3.0
    path: ^1.9.0
    shared_preferences: ^2.3.3
    flutter_riverpod: ^2.5.1
    riverpod_annotation: ^2.3.5
    provider: ^6.1.2
    flutter_gen_runner: ^5.4.0
    flutter_file_dialog: ^3.0.2
    flutter_smart_dialog: ^4.9.8+5
    fluttertoast: ^8.2.6

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^3.0.0
    test: any
    build_runner: ^2.4.12
    custom_lint: ^0.6.7
    riverpod_generator: ^2.4.3
    riverpod_lint: ^2.3.13

flutter:
    uses-material-design: true
    generate: true
    assets:
        - assets/fonts/SourceHanSerifSC-Regular.otf
        - pubspec.yaml
        - assets/foliate-js/
        - assets/foliate-js/vendor/
        - assets/foliate-js/vendor/pdfjs/

    fonts:
        - family: SourceHanSerif
          fonts:
              - asset: assets/fonts/SourceHanSerifSC-Regular.otf
