name: hreader
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
    sdk: ^3.5.4

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.8
    sqflite_common_ffi: ^2.3.4+3
    path_provider: ^2.1.5
    logging: ^1.3.0
    path: ^1.9.0

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^4.0.0

flutter:
    uses-material-design: true
